version: '3.9'

services:
  varnish:
    build: ./varnish
    ports:
      - 80:80
    depends_on:
      - nginx

  nginx:
    build: ./nginx
    restart: always
    depends_on:
      - wordpress
    volumes:
      - demo-wordpress:/var/www/html

  wordpress:
    image: wordpress:php7.1-fpm
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_PASSWORD: example
    depends_on:
      - mysql
    volumes:
      - demo-wordpress:/var/www/html

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - demo-db:/var/lib/mysql

volumes:
  demo-db:
  demo-wordpress:
